### PR TITLE
Replace _.truncate, save memory.

### LINKED ISSUE #53: Some of Lodash's string functions may be consuming a lot of memory on AWS Lambda
## Description

While working on file uploads with a CLI App, we've seen regular errors from Lambda and our function invocations dying. Recently, I enabled logging on one of these functions and found this very brief JS stacktrace:

That `unicodeToArray` got me curious. Looking at [Lodash source](https://github.com/lodash/lodash/blob/d10b44bdef2b735865c493fbaec8687ec8998aef/.internal/unicodeToArray.js#L38), we see this is indeed running a regular expression on whatever comes into it. Turns out this function is used by `stringToArray`, which is called by lots of Lodash functions in the trim, pad, and truncate realm.

With this bit of a hint, I went hunting and was able to find [this use of truncate](https://github.com/zapier/zapier-platform-core/blob/5fed875579a82f7edc8a56cc7ff014b5503fc098/src/tools/create-logger.js#L12) by our logger.

My theory is this: When a large file like a 25 MB movie gets passed through lambda, our logger is running `_.truncate()` on the raw binary string of data. Underhood, Lodash is running that regular expression on the binary string and it's causing massive amounts of memory usage.

## Replicating

This is the hard part. I had a consistent failure scenario, made a tweak locally to our logger, uploaded it in a test app. Errors went away! Then I reverted the fix and continued to see success, so I'm not positive what's happening anymore.

### PR DESCRIPTION
**Pull request by BrunoBernardino**
Fixes #53

Memory usage for truncating a 25MB file went from a 900-1000MB spike to a **130-160MB** spike! I also confirmed the output matched in both situations (`_.truncate()` actually just "appended" the `omission`, while now we make sure the string doesn't go over the defined length _including_ the `suffix`, but I think it like it better this way).

Also, plenty of tests were added for it, and a few other places that were using `_.truncate()` were updated too.

### CODE REVIEW

File: src/tools/data.js [hunk 1]
```diff
@@ -128,6 +128,20 @@ const flattenPaths = (data, sep) => {
...
 
+// A simpler, and memory-friendlier version of _.truncate()
+const simpleTruncate = (string, length, suffix) => {
+  if (!string || !string.toString || string.toString().length === 0) {
+    return '';
+  }
+
+  if (string.toString().length > length) {
+    const cutoff = (suffix ? length - suffix.length : length);
+    return string.toString().substr(0, cutoff) + (suffix ? suffix : '');
```
Comment (bcooksey) [inline src/tools/data.js]: Instead of invoking `toString()` three times, could we put that in a variable?

File: test/misc-tools.js [hunk 2]
```diff
@@ -55,6 +55,30 @@ describe('Tools', () => {
...
+      {value: () => {}, length: 5, suffix: '...', expected: '()...'},
+      {value: {yeah: true}, length: 8, suffix: '...', expected: '[obje...'},
+      {value: 'Something', length: 5, suffix: undefined, expected: 'Somet'},
+      {value: 'Something', length: 5, suffix: '...', expected: 'So...'},
+      {value: new Buffer('Something'), length: 7, suffix: ' [...]', expected: 'S [...]'},
+      {value: 'Something', length: 0, suffix: '...', expected: '...'},
+      {value: 'Something', length: 8, suffix: '...', expected: 'Somet...'},
+      {value: 'Something', length: 9, suffix: '...', expected: 'Something'},
+      {value: 'Something', length: 15, suffix: '...', expected: 'Something'},
+    ];
```
Comment (bcooksey) [inline test/misc-tools.js]: Phenomenal test!

**Review by bcooksey — APPROVED** [review]
One suggestion for efficiency, but otherwise this looks good.

Also, when digging into Lodash I recall them jumping over hoops to do special handling with unicode. I have not been able to figure why though, and can't find a test suite in the source for clues

**Comment by ibolmo** [comment]
(looking at this via phone) The Unicode jumping, I believe, is that the
length of the string varies. JS expects utf-8 but utf-16 strings will be
longer length.

-- 
Olmo Maldonado
Partners and Platform Engineer – Zapier.com

**Comment by bcooksey** [comment]
Also cc @kola-er. @BrunoBernardino was able to get a patch in, so you should be able to use this once it merges for DropBox!

**Comment by kola-er** [comment]
@bcooksey Yeah, I've been doing something similar locally. I just pulled and tested with it; the weirdness in memory usage is gone. Thanks @BrunoBernardino

File: test/misc-tools.js (hunk 2 above)
Comment (BrunoBernardino) [reply test/misc-tools.js]: I'll add some unicode tests.
